SELECT EMAIL,
       ADDRESS_NAME,
       FIRST_VALUE(ADDRESS_ID) OVER (PARTITION BY EMAIL ORDER BY TIMESTAMP) AS address_id,
       FIRST_VALUE(TIMESTAMP) OVER (PARTITION BY EMAIL ORDER BY TIMESTAMP) AS timestamp
FROM DREW_DB.SHOPIFY_TEST.USERS